name: on-push-login-page
on:
  push:
    branches:
      - login-page
jobs:
  UI_test:
    name: UI Test (login-page branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run login-page-test
  style_test:
    name: Coding Style Test (login-page branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx prettier --check .
  lint_JS_test:
    name: Linting JS Test (login-page branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx eslint .
