name: on-push-merging
on:
  push:
    branches:
      - merging
jobs:
  unit_test:
    name: unit Test (merging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run unit-test
  UI_test:
    name: UI Test (merging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run merging-test
  style_test:
    name: Coding Style Test (merging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx prettier --check .
  lint_JS_test:
    name: Linting JS Test (merging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx eslint .
