name: on-push-main-staging
on:
  push:
    branches:
      - main-staging
jobs:
  unit_test:
    name: unit Test (main-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run unit-test
  UI_test:
    name: UI Test (main-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run main-staging-test
  style_test:
    name: Coding Style Test (main-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx prettier --check .
  lint_JS_test:
    name: Linting JS Test (main-staging branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx eslint .
