name: on-push-testing
on:
  push:
    branches:
      - testing
jobs:
  style_test:
    name: Coding Style Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx prettier --check .
